# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# Short command for rebuilding and restarting
#   $ docker-compose up -d --build
# To stop containers:
#  $ docker-compose stop
# To clean up containers/images/networks:
#  $ docker system prune
version: '3'
networks:
  frontend:
    driver: bridge
  database:
    driver: bridge
services:
  webgme:
    build:
      context: .
    depends_on:
    - mongo
    volumes:
    - blob-storage:/blob-local-storage
    networks:
    - database
    - frontend
    ports:
    - 8888:8888
    environment:
    - NODE_ENV=docker
  mongo:
    image: mongo:8.0.3
    #ports:
    #- 27017:27017 # Uncomment to expose mongo-port on host
    volumes:
    - mongo-db:/data/db
    networks:
    - database
volumes:
  mongo-db:
  blob-storage:
